[package]
name = "graphmage-cli"
edition = "2021"
version.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4"
